---
- name: OS-specific tasks
  include_tasks: "{{ ansible_distribution|lower }}.yml"


- name: Install via pyenv
  include_tasks: pyenv.yml
  when: python3_pyenv != None

- name: Add local Python path to login file
  lineinfile:
    line: "export PATH={{ python3_local }}:$PATH"
    path: "{{ python3_bashrc }}"
    create: true
    state: present
    mode: 0644
  become: true