---
- hosts: "{{ host }}"
  name: "Install python3"
  tasks:
    - name : Check if Python/{{ansible_distribution|lower}}{{ ansible_distribution_major_version}}.yml exists
      ansible.builtin.stat:
        path: "{{playbook_dir}}/python/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml"
      register: playbook_name_with_version
    - name : Check if python/{{ansible_distribution|lower}}.yml exists
      ansible.builtin.stat:
        path: "{{playbook_dir}}/python/{{ ansible_distribution|lower}}.yml"
      register: playbook_name
      when : not playbook_name_with_version.stat.exists and playbook_name_with_version.stat.exists is defined
    - name : "Try include playbook {{ansible_distribution|lower}}{{ansible_distribution_major_version}}.yml"
      include_tasks:
        file : "{{playbook_name_with_version.stat.path}}"
      when : playbook_name.skipped is defined and (playbook_name_with_version.stat.exists is defined and playbook_name_with_version.stat.exists)
    - name : "Try include playbook {{ansible_distribution|lower}}.yml ({{ansible_distribution|lower}}{{ansible_distribution_major_version}}.yml not found)"
      include_tasks:
        file : "{{playbook_name.stat.path}}"
      when : playbook_name_with_version.stat.exists is defined and not playbook_name_with_version.stat.exists and (playbook_name.stat.exists is defined and playbook_name.stat.exists)
      register : result_default
    - name: "{{ansible_distribution|lower}}{{ansible_distribution_major_version}}.yml"
      ansible.builtin.debug:
        msg : "{{playbook_name_with_version}}"
    - name: "{{ansible_distribution|lower}}.yml"
      ansible.builtin.debug:
        msg : "{{playbook_name}}"
    - name: "{{ansible_distribution|lower}}.yml skipped"
      ansible.builtin.debug:
        msg : "{{ansible_distribution|lower}}.yml has been skipped. See logs to see what playbook has been executed."
      when: playbook_name is skipped
