services:
  mariadb:
    image: mariadb:10.9
    container_name: mariadb
    hostname: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=keystone
      - MYSQL_USER=keystone
      - MYSQL_PASSWORD=keystone_db_pass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      swift-clusterTEST:
        ipv4_address: 10.5.3.3
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3


  memcached:
    image: memcached:alpine
    networks:
      swift-clusterTEST:
        ipv4_address: 10.5.3.4

  keystone:
    image: keystone:master-ubuntu_jammy
    container_name: keystone
    restart: always
    ports:
      - "5000:5000"
      - "35357:35357"   # Admin endpoint
    volumes:
      - ./conf/etc/keystone:/etc/keystone:rw
      - ./conf/apache2/keystone/ports.conf:/etc/apache2/ports.conf:ro
      - ./conf/apache2/keystone/sites-available/keystone.conf:/etc/apache2/sites-available/keystone.conf:ro
      - ./conf/python/keystone/wsgi/wsgi.py:/var/lib/openstack/lib/python3.10/site-packages/keystone/server/wsgi.py
      - ./scripts/init-keystone.sh:/entrypoint.sh:ro
      - keystone_data:/var/lib/keystone
    command: /entrypoint.sh
    depends_on:
        mariadb:
          condition: service_healthy
        memcached:
          condition: service_started   # memcached est prêt quasi immédiatement
    networks:
      swift-clusterTEST:
        ipv4_address: 10.5.3.1

  horizon:
    image: horizon:master-ubuntu_jammy
    container_name: horizon
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./conf/etc/horizon/local_settings.py:/local_settings.py:ro
      - ./conf/apache2/horizon/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./scripts/init-horizon.sh:/entrypoint.sh:ro
    command: /entrypoint.sh
    depends_on:
      - keystone
    networks:
      swift-clusterTEST:
        ipv4_address: 10.5.3.2

volumes:
  mariadb_data:
  keystone_data:


networks:
  swift-clusterTEST:
    name: swift-cluster
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1