services:
  initswift:
    profiles:
      - backend
      - storage
      - datalake
    build:
      context: ./openstackSwift/
      dockerfile: Dockerfile.base
    volumes:
      - ./openstackSwift/conf/:/etc/swift
      - ./openstackSwift/data/:/srv/
      - ./openstackSwift/scripts:/scripts/
    command: sh /scripts/init.sh
    privileged: true
    networks:
      - swift_cluster

  management-1:
    profiles:
      - backend
      - storage
      - datalake
    hostname: management-1
    build:
      context: ./openstackSwift/
      dockerfile: Dockerfile.base
    entrypoint: ["sh","/scripts/management/management-1.sh"]
    volumes:
        - ./openstackSwift/conf/:/etc/swift
        - ./openstackSwift/scripts:/scripts/
    privileged: true
#    ports:
#      - "8080:8080"
    restart: always
    networks:
      swift_cluster:
        ipv4_address: 10.5.10.1
    depends_on:
      initswift:
        condition: service_completed_successfully
  storage-1:
    profiles:
      - backend
      - storage
      - datalake
    hostname: storage-1
    build:
      context: openstackSwift/
      dockerfile: Dockerfile.base
    entrypoint: ["sh","/scripts/storage/storage-1.sh"]
    volumes:
        - ./openstackSwift/conf/:/etc/swift
        - ./openstackSwift/data/:/internal_dev/
        - ./openstackSwift/scripts:/scripts/
        - ./openstackSwift/rsyncd/rsyncd-1.conf:/etc/rsyncd.conf
    privileged: true
    restart: always
    networks:
      swift_cluster:
        ipv4_address: 10.5.1.1
    depends_on:
      initswift:
        condition: service_completed_successfully
  hub:
    build:
      context: ./jupyter/
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: 5.3.0
    profiles:
      - datalake
      - frontend
      - process
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    networks:
      jupyterhub-network:
      swift_cluster:
          ipv4_address: 10.5.100.1

    volumes:
      # The JupyterHub configuration file
      - ./jupyter/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - /var/run/docker.sock:/var/run/docker.sock:rw
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - ./jupyter/jupyterhub-data:/data
    ports:
      - 8000:8000
    environment:
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: admin
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: cors_base-notebook:latest
      #DOCKER_NOTEBOOK_IMAGE: quay.io/jupyter/base-notebook:latest
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work


  web_gui:
    profiles:
      - frontend
      - webgui
      - datalake
    build:
      context: ./frontend/
      dockerfile: Dockerfile.web_gui
    image: web_gui
    container_name: web_gui
    volumes:
      - ./frontend/web_gui:/opt/app/web_gui/
    ports :
      - 3000:3000
    networks:
        swift_cluster:
          ipv4_address: 10.5.255.1
  nginx-proxy:
    profiles:
      - frontend
      - datalake
    build:
      context: ./RESTapi/
      dockerfile: Dockerfile.nginx
    restart: always
    volumes:
      - ./RESTapi/nginx/default.conf:/tmp/default.conf
    environment:
      - FLASK_SERVER_ADDR=flask-app:8000
    ports:
      - "80:80"
    depends_on:
      - flask-app
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
    networks:
      swift_cluster:
        ipv4_address: 10.5.255.254
  flask-app:
    build:
      context: ./RESTapi/
      dockerfile: Dockerfile.flask
    restart: always
    profiles:
      - frontend
      - RESTApi
      - datalake
    volumes:
      - "./RESTapi/flask/app.py:/home/app/app.py"
    ports:
      - '5000:5000'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/flask-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:5000 app:app
    networks:
      swift_cluster:
        ipv4_address: 10.5.255.2



networks:
  jupyterhub-network:
    name: jupyterhub-network
  swift_cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
