FROM ubuntu:24.04


# Installation des dépendances
RUN apt  update -y && apt upgrade -y && apt  install -y \
    curl \
    gcc \
    memcached \
    rsync \
    sqlite3 \
    xfsprogs \
    git-core \
    libffi-dev \
    python3-setuptools \
    liberasurecode-dev \
    libssl-dev \
    python3-coverage \
    python3-dev \
    python3-pytest \
    python3-xattr \
    python3-eventlet \
    python3-greenlet \
    python3-pastedeploy \
    python3-pip \
    python3-dnspython \
    ubuntu-cloud-keyring && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y software-properties-common apt-transport-https && \
    rm -rf /var/lib/apt/lists/*


RUN add-apt-repository cloud-archive:epoxy

RUN apt install -y swift swift-account swift-container swift-object swift-proxy python3-swiftclient memcached




# Les commandes executées
# mkdir -p /etc/swift /var/run/swift /var/cache/swift /srv/node/sdb1
# chown -R swift:swift /etc/swift /var/run/swift /var/cache/swift /srv/node
cat > /etc/swift/swift.conf << EOF
[swift-hash]
swift_hash_path_suffix = $(openssl rand -hex 10)
swift_hash_path_prefix = $(openssl rand -hex 10)

[storage-policy:0]
name = Policy-0
default = yes
EOF
chown -R swift:swift /etc/swift

cd /etc/swift




# Création des répertoires nécessaires pour Swift
# RUN mkdir -p /etc/swift /var/cache/swift /var/run/swift && \
#    chown -R nobody:nogroup /var/cache/swift /var/run/swift

# Commande pour garder le conteneur en vie
CMD ["tail", "-f", "/dev/null"]