[DEFAULT]
devices = /srv/node/
bind_ip = 0.0.0.0
bind_port = 6201
workers = 2
log_facility = LOG_LOCAL7

[pipeline:main]
pipeline = healthcheck recon container-server

[app:container-server]
use = egg:swift#container

[filter:recon]
use = egg:swift#recon

[filter:healthcheck]
use = egg:swift#healthcheck


[object-replicator]

[object-updater]

[object-auditor]
