[DEFAULT]
bind_ip = 0.0.0.0
bind_port = 6002
devices = /srv/node/sdb0
workers = auto
client_timeout = 60
node_timeout = 10
conn_timeout = 0.5
log_level = INFO
log_address = /dev/log
mount_check = true
fallocate_reserve = 1%
db_preallocation = off

[pipeline:main]
pipeline = healthcheck recon account-server

[app:account-server]
use = egg:swift#account
replication_server = true

[filter:healthcheck]
use = egg:swift#healthcheck

[filter:recon]
use = egg:swift#recon
recon_cache_path = /var/cache/swift

[account-replicator]
interval = 30
concurrency = 8
per_diff = 1000
max_diffs = 100
databases_per_second = 50
rsync_module = {replication_ip}::account
reclaim_age = 604800
handoffs_only = false
handoff_delete = auto

[account-auditor]
interval = 1800
accounts_per_second = 200

[account-reaper]
concurrency = 25
interval = 3600
delay_reaping = 0
reap_warn_after = 2592000