[memcache]
memcache_servers = 10.5.2.1:11211
memcache_max_connections = 2
connect_timeout = 0.3
pool_timeout = 1.0
tries = 3
io_timeout = 2.0
error_suppression_interval = 60
error_suppression_limit = 10
tls_enabled = false
item_size_warning_threshold = -1