[DEFAULT]
bind_ip = 0.0.0.0
bind_port = 6000
devices = /srv/node
workers = auto
client_timeout = 60
node_timeout = 10
conn_timeout = 0.5
log_level = INFO
log_address = /dev/log
mount_check = true
fallocate_reserve = 1%
keep_cache_size = 5242880

[pipeline:main]
pipeline = healthcheck recon object-server

[app:object-server]
use = egg:swift#object
max_upload_time = 86400
keep_cache_private = false
etag_validate_pct = 100
mb_per_sync = 512
allowed_headers = Content-Disposition, Content-Encoding, X-Delete-At, X-Object-Manifest, Cache-Control, Content-Language, Expires, X-Robots-Tag
replication_server = true
replication_concurrency = 4
replication_concurrency_per_device = 1

[filter:healthcheck]
use = egg:swift#healthcheck

[filter:recon]
use = egg:swift#recon
recon_cache_path = /var/cache/swift

[filter:backend_ratelimit]
use = egg:swift#backend_ratelimit
backend_ratelimit_conf_path = /etc/swift/backend-ratelimit.conf

[object-replicator]
interval = 30
concurrency = 1
rsync_timeout = 900
rsync_bwlimit = 0
rsync_module = {replication_ip}::object
http_timeout = 60
lockup_timeout = 1800
handoffs_first = false
handoff_delete = auto

[object-reconstructor]
interval = 30
concurrency = 1
handoffs_only = false
rebuild_handoff_node_count = 2
max_objects_per_revert = 0
quarantine_threshold = 0

[object-updater]
interval = 300
concurrency = 8
objects_per_second = 50
max_objects_per_container_per_second = 0
report_interval = 300

[object-auditor]
interval = 30
files_per_second = 20
bytes_per_second = 10000000
zero_byte_files_per_second = 50
rsync_tempfile_timeout = auto

[object-expirer]
interval = 300
tasks_per_second = 50
reclaim_age = 604800