[DEFAULT]
bind_ip = 0.0.0.0
bind_port = 8080
workers = auto
client_timeout = 60
node_timeout = 10
conn_timeout = 0.5
error_suppression_interval = 60
error_suppression_limit = 10
log_level = INFO
log_address = /dev/log
expose_info = true

[pipeline:main]
pipeline = catch_errors healthcheck proxy-logging cache tempauth s3api proxy-server

[app:proxy-server]
use = egg:swift#proxy
allow_account_management = true
account_autocreate = true
recheck_account_existence = 60
recheck_container_existence = 60
sorting_method = shuffle

[filter:tempauth]
use = egg:swift#tempauth
reseller_prefix = AUTH_
auth_prefix = /auth/
token_life = 86400
delay_auth_decision = true
storage_url_scheme = http
user_admin_admin = .admin .reseller_admin
user_test_tester = testing .admin

[filter:s3api]
use = egg:swift#s3api
auth_pipeline_check = true
allow_multipart_uploads = true
max_bucket_listing = 1000
s3_acl = false
location = us-east-1
dns_compliant_bucket_names = true

[filter:healthcheck]
use = egg:swift#healthcheck

[filter:cache]
use = egg:swift#memcache
memcache_servers = 10.5.2.1:11211
memcache_max_connections = 2

[filter:proxy-logging]
use = egg:swift#proxy_logging
access_log_name = proxy-server
access_log_level = INFO
access_log_address = /dev/log
access_log_headers = true
reveal_sensitive_prefix = 0

[filter:catch_errors]
use = egg:swift#catch_errors