[database]
connection = mysql+pymysql://keystone:keystone_db_pass@mariadb/keystone

[token]
provider = fernet

[cache]
enabled = true
backend = oslo_cache.memcache_pool
memcache_servers = memcached:11211
[EXTRA]
servername = keystone