#!/bin/bash
set -e
: "${OS_PASSWORD:=admin}" # change in production
echo OS_PASSWORD

# Configuration Apache (toujours, idempotent)
a2enmod wsgi
a2dissite 000-default || true
a2ensite keystone

# === OIDC federation with Keycloak (Apache mod_auth_openidc) ===
# Rendered at runtime so the Keycloak URL / client can be changed (or pointed to
# an external Keycloak) by editing conf.env only — no image rebuild required.
: "${FEDERATION_ENABLED:=false}"
if [ "${FEDERATION_ENABLED,,}" = "true" ]; then
    : "${KEYCLOAK_ISSUER:?KEYCLOAK_ISSUER is required when FEDERATION_ENABLED=true}"
    : "${KEYCLOAK_JWKS_URI:?KEYCLOAK_JWKS_URI is required when FEDERATION_ENABLED=true}"
    : "${OIDC_CRYPTO_PASSPHRASE:?OIDC_CRYPTO_PASSPHRASE is required when FEDERATION_ENABLED=true}"
    : "${KEYCLOAK_CLIENT_ID:=keystone}"
    : "${KEYCLOAK_CLIENT_SECRET:=}"
    : "${KEYCLOAK_IDP_ID:=keycloak}"
    : "${KEYCLOAK_PROTOCOL_ID:=openid}"
    : "${KEYSTONE_PUBLIC_URL:=http://localhost:5000}"

    echo "Federation enabled : configuring mod_auth_openidc against ${KEYCLOAK_ISSUER}"
    if [ ! -f /etc/apache2/mods-available/auth_openidc.load ]; then
        echo "ERROR: mod_auth_openidc is not installed in this Keystone image." >&2
        echo "       Rebuild it (build.sh installs libapache2-mod-auth-openidc)." >&2
        exit 1
    fi
    a2enmod auth_openidc

    # Strip any trailing slash from the public URL to build a clean redirect URI.
    KEYSTONE_PUBLIC_URL="${KEYSTONE_PUBLIC_URL%/}"
    OIDC_REDIRECT_URI="${KEYSTONE_PUBLIC_URL}/v3/OS-FEDERATION/identity_providers/${KEYCLOAK_IDP_ID}/protocols/${KEYCLOAK_PROTOCOL_ID}/auth/redirect"

    # mod_auth_openidc rejects a plain-http OIDCOAuthVerifyJwksUri (HTTPS only).
    # For an external HTTPS Keycloak we use the remote JWKS directly (supports key
    # rotation). For the bundled HTTP Keycloak we fetch the realm signing
    # certificate(s) once and validate access tokens locally (CertFiles accepts
    # local files), waiting for Keycloak to be up.
    case "$KEYCLOAK_JWKS_URI" in
      https://*)
        OIDC_VERIFY_DIRECTIVE="OIDCOAuthVerifyJwksUri ${KEYCLOAK_JWKS_URI}"
        ;;
      *)
        echo "JWKS is plain HTTP : fetching Keycloak signing cert(s) for local validation..."
        CERT_DIR=/etc/keystone/keycloak-certs
        mkdir -p "$CERT_DIR"
        # python3 may not be on PATH (minimal base) : fall back to keystone's venv.
        PYTHON_BIN="$(command -v python3 || true)"
        if [ -z "$PYTHON_BIN" ] && [ -x /var/lib/openstack/bin/python3 ]; then
            PYTHON_BIN=/var/lib/openstack/bin/python3
        fi
        if [ -z "$PYTHON_BIN" ]; then
            echo "ERROR: python3 not found to fetch the Keycloak signing certificate" >&2
            exit 1
        fi
        CERT_ARGS="$("$PYTHON_BIN" - "$KEYCLOAK_JWKS_URI" "$CERT_DIR" <<'PY'
import sys, json, time, urllib.request
jwks_uri, cert_dir = sys.argv[1], sys.argv[2]
data = None
for _ in range(40):
    try:
        with urllib.request.urlopen(jwks_uri, timeout=5) as r:
            data = json.load(r)
        break
    except Exception as e:
        sys.stderr.write("waiting for Keycloak JWKS (%s)...\n" % e)
        time.sleep(3)
if data is None:
    sys.stderr.write("ERROR: could not fetch JWKS from %s\n" % jwks_uri)
    sys.exit(1)
args = []
for k in data.get("keys", []):
    if k.get("use", "sig") != "sig" or not k.get("x5c"):
        continue
    kid = k.get("kid", "key")
    der = k["x5c"][0]
    pem = ("-----BEGIN CERTIFICATE-----\n"
           + "\n".join(der[i:i + 64] for i in range(0, len(der), 64))
           + "\n-----END CERTIFICATE-----\n")
    path = "%s/%s.pem" % (cert_dir, kid)
    with open(path, "w") as f:
        f.write(pem)
    args.append("%s#%s" % (kid, path))
if not args:
    sys.stderr.write("ERROR: no signing certificate (x5c) in JWKS\n")
    sys.exit(1)
print(" ".join(args))
PY
)"
        if [ -z "$CERT_ARGS" ]; then
            echo "ERROR: failed to obtain Keycloak signing certificate from $KEYCLOAK_JWKS_URI" >&2
            exit 1
        fi
        OIDC_VERIFY_DIRECTIVE="OIDCOAuthVerifyCertFiles ${CERT_ARGS}"
        ;;
    esac

    cat > /etc/apache2/conf-available/keystone-oidc.conf <<OIDCCONF
# Generated by init-keystone.sh from conf.env - do not edit by hand.
# Verbose OIDC/OAuth logging to diagnose token validation (lower to warn later).
LogLevel auth_openidc:debug
#
# Keystone acts here as an OAuth2 *resource server* : the Flask BFF (and the CLI
# v3oidc* plugins) obtain a Keycloak access token and POST it to the federated
# auth endpoint as a bearer token. mod_auth_openidc validates that token against
# Keycloak's JWKS (reached on the INTERNAL URL) and exposes its claims as
# HTTP_OIDC_* request env vars, matching remote_id_attribute=HTTP_OIDC_ISS and
# the federation mapping rules.

# OIDCCryptoPassphrase + OIDCRedirectURI are mandatory whenever the module is
# active (even in OAuth2-only mode); the redirect URI is just a placeholder here.
OIDCCryptoPassphrase ${OIDC_CRYPTO_PASSPHRASE}
OIDCRedirectURI ${OIDC_REDIRECT_URI}
OIDCClaimPrefix "HTTP_OIDC_"
OIDCPassClaimsAs both
# Multi-valued claims (e.g. groups) are joined with this delimiter. Keystone's
# mapped plugin splits assertion values on ";" : keep them aligned, otherwise a
# user in several Keycloak groups would never match the FEDERATED_GROUP rule.
OIDCClaimDelimiter ";"
# Which token claim becomes the Apache remote user (default "sub" is not always
# resolvable for Keycloak access tokens); preferred_username always is.
OIDCOAuthRemoteUserClaim preferred_username

# Validate Keycloak access tokens (JWT) : remote JWKS (https) or local signing
# certificate(s) fetched from the realm above (bundled http Keycloak).
${OIDC_VERIFY_DIRECTIVE}

# Federated authentication endpoint used by Flask BFF + CLI (bearer access token)
<Location ~ "/v3/OS-FEDERATION/identity_providers/${KEYCLOAK_IDP_ID}/protocols/${KEYCLOAK_PROTOCOL_ID}/auth">
    AuthType oauth20
    Require valid-user
</Location>

# --- Optional : browser WebSSO through Horizon (OIDC code flow) ---------------
# Requires this container to reach the PUBLIC Keycloak metadata URL and a client
# secret. Uncomment + ensure ${KEYCLOAK_ISSUER} is reachable from Keystone.
#OIDCProviderMetadataURL ${KEYCLOAK_ISSUER}/.well-known/openid-configuration
#OIDCClientID ${KEYCLOAK_CLIENT_ID}
#OIDCClientSecret ${KEYCLOAK_CLIENT_SECRET}
#OIDCResponseType "code"
#OIDCScope "openid email profile"
#<Location ~ "/v3/auth/OS-FEDERATION/websso/${KEYCLOAK_PROTOCOL_ID}">
#    AuthType openid-connect
#    Require valid-user
#</Location>
#<Location ~ "/v3/auth/OS-FEDERATION/identity_providers/${KEYCLOAK_IDP_ID}/protocols/${KEYCLOAK_PROTOCOL_ID}/websso">
#    AuthType openid-connect
#    Require valid-user
#</Location>
OIDCCONF

    a2enconf keystone-oidc
else
    echo "Federation disabled : skipping mod_auth_openidc configuration"
    a2disconf keystone-oidc 2>/dev/null || true
fi

apache2ctl configtest

# Initialisation unique
if [ ! -f /var/lib/keystone/.initialized ]; then
    echo "Initialisation de Keystone..."
    keystone-manage db_sync
    keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
    keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

    # Sécurise les clés
    chmod 700 /etc/keystone/fernet-keys /etc/keystone/credential-keys

    keystone-manage bootstrap \
        --bootstrap-password $OS_PASSWORD \
        --bootstrap-username admin \
        --bootstrap-project-name admin \
        --bootstrap-role-name admin \
        --bootstrap-service-name keystone \
        --bootstrap-region-id RegionOne \
        --bootstrap-admin-url http://keystone:35357/v3 \
        --bootstrap-internal-url http://keystone:5000/v3 \
        --bootstrap-public-url http://keystone:5000/v3

    touch /var/lib/keystone/.initialized
fi
#echo "application = initialize_public_application()" >> /var/lib/openstack/lib/python3.10/site-packages/keystone/server/wsgi.py
exec apache2ctl -D FOREGROUND