services:
  init:
    build:
      context: .
      dockerfile: Dockerfile.base
    volumes:
      - ./conf/:/etc/swift
      - ./data/:/srv/
    command: sh /deploy_swift.sh
    networks:
      - swift_cluster
  proxy-1:
    hostname: proxy-1
    build:
      context: .
      dockerfile: Dockerfile.base

    command: [ "swift-proxy-server", "/etc/swift/proxy-server.conf", "verbose" ]
    ports:
      - "8080:8080"
    volumes:
      - ./conf/:/etc/swift:ro
      - swift_cache:/var/cache/swift
      - ./data:/srv/

    restart: always
    networks:
      swift_cluster:
        ipv4_address: 10.5.1.1
    depends_on:
      init:
        condition: service_completed_successfully
#      memcached-1:
#        condition: service_healthy
  account-1:
    hostname: account-1
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.base
    entrypoint: ["/opt/swift-scripts/start-service.sh"]
    command: ["swift-account-server", "/etc/swift/account-server.conf", "verbose"]
    environment:
      - DEV=sdb0
    volumes:
      - swift_conf:/etc/swift:ro
      - swift_data:/srv/node
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "mountpoint -q /srv/node/sdb0 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      swift_cluster:
        ipv4_address: 10.5.3.1
    depends_on:
      init:
        condition: service_completed_successfully

  memcached-1:
    hostname: memcached-1
    build:
      context: .
      dockerfile: Dockerfile.base

    command: ["memcached", "-u", "root", "-l", "0.0.0.0"]
    ports:
      - "11211:11211"
    volumes:
      - swift_conf:/etc/swift:ro
      - swift_cache:/var/cache/swift

    restart: always
    networks:
      swift_cluster:
        ipv4_address: 10.5.2.1

volumes:
  swift_conf:
  swift_data:
  swift_cache:

networks:
  swift_cluster:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1