apiVersion: v1
kind: Service
metadata:
  name: swift-proxy                         # joignable dans le namespace par http://swift-proxy:8080
  namespace: datalake
  labels:
    app.kubernetes.io/name: swift
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: raw-data-zone
spec:
  type: ClusterIP                           # interne au cluster ; l'exposition publique viendra par l'Ingress
  selector:
    app.kubernetes.io/name: swift
    app.kubernetes.io/component: proxy
  ports:
    - name: proxy
      port: 8080
      targetPort: proxy
