FROM ubuntu:24.04

# Installation des dépendances système
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
    curl \
    gcc \
    memcached \
    rsync \
    sqlite3 \
    xfsprogs \
    git \
    libffi-dev \
    liberasurecode-dev \
    libssl-dev \
    python3-coverage \
    python3-dev \
    python3-pytest \
    python3-xattr \
    python3-eventlet \
    python3-greenlet \
    python3-pastedeploy \
    python3-pip \
    python3-dnspython \
    ubuntu-cloud-keyring \
    software-properties-common \
    # nécessaire pour tester les config réseau, à supprimer à terme
    iputils-ping  iproute2 \
    apt-transport-https iputils-ping  iproute2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
