apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --profile datalake
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nginx-proxy
  name: nginx-proxy
spec:
  ports:
    - name: "7000"
      port: 7000
      targetPort: 80
  selector:
    io.kompose.service: nginx-proxy
