apiVersion: v1
kind: Service
metadata:
  name: memcached                           # memcached:11211 dans les confs (Swift proxy, Keystone…)
  namespace: datalake
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: datalake
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: memcached
  ports:
    - name: memcached
      port: 11211
      targetPort: memcached
