---

- import_playbook: "{{playbook_dir}}/../../base/tasks/docker_install.yml"
  vars:
    host: process_zone_apache_airflow


- name : Download files
  vars_files: ../vars/main.yml
  hosts: process_zone_apache_airflow
  tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      var: hostvars.metadata_management_zone_mongodb.BUILD_DIR
  - name: Create a build directory
    ansible.builtin.file:
      path: "{{ hostvars.process_zone_apache_airflow.BUILD_DIR}}/process_zone_apache_airflow"
      state: directory
      mode: "0755"
  - name: get Dockerfile for container building
    get_url:
      url : 'https://airflow.apache.org/docs/apache-airflow/2.1.2/docker-compose.yaml'
      dest : "{{ hostvars.process_zone_apache_airflow.BUILD_DIR}}/process_zone_apache_airflow"
    become : yes
  - name: Stop and delete any container
    shell :
      cmd : "docker stop $(docker ps -a -q); docker rm $(docker ps -a -q)"
    become : yes
    ignore_errors: yes
  - name : Create env and folders
    shell :
      cmd : 'mkdir -p ./dags ./logs ./plugins ; echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=0" > .env'
      chdir: "{{ hostvars.process_zone_apache_airflow.BUILD_DIR}}/process_zone_apache_airflow"
    become: yes
  - name : Init Airflow containers
    shell:
      cmd : 'docker-compose up airflow-init'
      chdir : "{{ hostvars.process_zone_apache_airflow.BUILD_DIR}}/process_zone_apache_airflow"
    become : yes
    register : output
  - ansible.builtin.debug:
      var: output
  - name : Start Airflow
    shell :
      cmd : '(docker-compose up &); sleep 10'
      chdir : "{{ hostvars.process_zone_apache_airflow.BUILD_DIR}}/process_zone_apache_airflow"
    become : yes
    register: output
  - ansible.builtin.debug:
      var: output
