#!/bin/bash
# Builds the Swift rings of the Kubernetes deployment from conf.env :
#   volumes/configmap_swift_rings.yml          account/container/object.ring.gz (mounted in /etc/swift by the pods)
#   volumes/configmap_swift_ring_builders.yml  account/container/object.builder (source of the rings, kept in the cluster)
#
# Rings are created ONCE : a new "create" assigns the partitions at random, so existing objects
# would no longer be where the ring looks for them. When the builders already exist in the
# cluster, they are fetched and only modified (set_replicas, add, rebalance).
# Removing a storage node is never automatic : swift-ring-builder <ring>.builder remove ...
#
# One device per storage pod, addressed by its stable DNS name (StatefulSet + headless Service) :
#   swift-storage-<i>.swift-storage.datalake.svc.cluster.local  6200 account / 6201 container / 6202 object, device d1
#
# Requires : docker with the Swift image built (swift-ring-builder runs inside it, through sudo
# when the user is not in the docker group), kubectl.
# ConfigMaps are limited to 1 MiB : fine for the builders up to a part power around 16.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONF_ENV="${CONF_ENV:-$SCRIPT_DIR/../../../conf.env}"
VOLUMES_PATH="$SCRIPT_DIR/volumes"

NAMESPACE="datalake"
STORAGE_NAME="swift-storage"              # name of the StatefulSet AND of its headless Service
DEVICE="d1"                               # volumeClaimTemplates name = /srv/node/d1 in the pods
SWIFT_IMAGE="${SWIFT_IMAGE:-swift-base:2.30.0}"
KUBECONFIG_FILE="${KUBECONFIG_FILE:-/etc/rancher/k3s/k3s.yaml}"
RINGS="account container object"
LABELS=(app.kubernetes.io/name=swift app.kubernetes.io/part-of=raw-data-zone)

if [ ! -f "$CONF_ENV" ]; then
  echo "Error: $CONF_ENV not found."
  exit 1
fi
export $(grep -v '^#' "$CONF_ENV" | sed 's/\r$//' | xargs)

for var in NB_STORAGE_NODE NODE_STORAGE_SIZE SWIFT_PART_POWER SWIFT_MIN_PART_HOURS; do
  if [ -z "${!var:-}" ]; then
    echo "Set $var in $CONF_ENV."
    exit 1
  fi
done

# 3 replicas at most : beyond, extra copies cost disk space without real gain
REPLICAS=$(( NB_STORAGE_NODE < 3 ? NB_STORAGE_NODE : 3 ))
# Weight = disk size in GB ("10GB" -> 10) : partitions are spread in proportion to it
WEIGHT=$(echo "$NODE_STORAGE_SIZE" | tr -dc '0-9')
WEIGHT="${WEIGHT:-1}"

for cmd in docker kubectl base64; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Error: $cmd is not installed."
    exit 1
  fi
done
# Docker through sudo when the user is not allowed to reach the daemon
DOCKER=(docker)
if ! docker info >/dev/null 2>&1; then
  DOCKER=(sudo docker)
  if ! sudo docker info >/dev/null 2>&1; then
    echo "Error: cannot reach the Docker daemon (sudo systemctl status docker)."
    exit 1
  fi
fi
if ! "${DOCKER[@]}" image inspect "$SWIFT_IMAGE" >/dev/null 2>&1; then
  echo "Error: image $SWIFT_IMAGE not found : build it first."
  exit 1
fi

K() { kubectl --kubeconfig "$KUBECONFIG_FILE" "$@"; }

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

# swift-ring-builder, run in the Swift image on the files of WORK_DIR
ring_builder() {
  "${DOCKER[@]}" run --rm --user "$(id -u):$(id -g)" -v "$WORK_DIR:/rings" -w /rings "$SWIFT_IMAGE" swift-ring-builder "$@"
}

port_of() {
  case "$1" in
    account)   echo 6200 ;;
    container) echo 6201 ;;
    object)    echo 6202 ;;
  esac
}

# write_configmap <name> <yaml file> <files...> : binary files land in binaryData
write_configmap() {
  local name=$1 file=$2
  shift 2
  local args=() src
  for src in "$@"; do
    args+=(--from-file="$src")
  done
  {
    echo "# Generated by create_rings.sh : edit nothing here, run the script again"
    K -n "$NAMESPACE" create configmap "$name" "${args[@]}" --dry-run=client -o yaml \
      | K label --local -f - "${LABELS[@]}" -o yaml
  } > "$file"
}

####################################
## EXISTING RINGS ?
####################################
# Unreachable cluster = stop : guessing "no rings" would recreate them from scratch
if ! EXISTING=$(K -n "$NAMESPACE" get configmap swift-ring-builders --ignore-not-found -o name); then
  echo "Error: cluster unreachable with $KUBECONFIG_FILE : cannot tell whether rings already exist."
  exit 1
fi

if [ -n "$EXISTING" ]; then
  echo "Rings found in the cluster : they are modified, never recreated."
  for ring in $RINGS; do
    K -n "$NAMESPACE" get configmap swift-ring-builders -o "jsonpath={.binaryData.$ring\.builder}" \
      | base64 -d > "$WORK_DIR/$ring.builder"
    if [ ! -s "$WORK_DIR/$ring.builder" ]; then
      echo "Error: $ring.builder missing in configmap swift-ring-builders."
      exit 1
    fi
  done
else
  echo "No rings in the cluster : creating them (part power $SWIFT_PART_POWER, $REPLICAS replica(s))."
  for ring in $RINGS; do
    ring_builder "$ring.builder" create "$SWIFT_PART_POWER" "$REPLICAS" "$SWIFT_MIN_PART_HOURS"
  done
fi

####################################
## REPLICAS + DEVICES + REBALANCE
####################################
for ring in $RINGS; do
  port=$(port_of "$ring")

  current=$(ring_builder "$ring.builder" | grep -o '[0-9.]* replicas' | head -n1 | cut -d' ' -f1)
  if [ "${current%%.*}" != "$REPLICAS" ]; then
    echo "$ring ring : replicas ${current%%.*} -> $REPLICAS"
    ring_builder "$ring.builder" set_replicas "$REPLICAS"
  fi

  for i in $(seq 0 $((NB_STORAGE_NODE - 1))); do
    host="$STORAGE_NAME-$i.$STORAGE_NAME.$NAMESPACE.svc.cluster.local"
    # search exits 2 when no device matches
    if ! ring_builder "$ring.builder" search --ip "$host" --port "$port" --device "$DEVICE" >/dev/null 2>&1; then
      echo "$ring ring : adding $host:$port/$DEVICE (weight $WEIGHT)"
      ring_builder "$ring.builder" add --region 1 --zone 1 --ip "$host" --port "$port" --device "$DEVICE" --weight "$WEIGHT"
    fi
  done

  # rebalance : 0 = done, 1 = warning (nothing to move, min_part_hours not elapsed...), 2 = error
  rc=0
  ring_builder "$ring.builder" rebalance || rc=$?
  if [ "$rc" -ge 2 ]; then
    echo "Error: rebalance of the $ring ring failed."
    exit 1
  fi
  # the .ring.gz is only written by a rebalance that moved partitions : always write it
  ring_builder "$ring.builder" write_ring >/dev/null
done

####################################
## YAML FILES
####################################
mkdir -p "$VOLUMES_PATH"
write_configmap swift-rings "$VOLUMES_PATH/configmap_swift_rings.yml" \
  "$WORK_DIR/account.ring.gz" "$WORK_DIR/container.ring.gz" "$WORK_DIR/object.ring.gz"
write_configmap swift-ring-builders "$VOLUMES_PATH/configmap_swift_ring_builders.yml" \
  "$WORK_DIR/account.builder" "$WORK_DIR/container.builder" "$WORK_DIR/object.builder"

echo "Generated :"
echo "  $VOLUMES_PATH/configmap_swift_rings.yml"
echo "  $VOLUMES_PATH/configmap_swift_ring_builders.yml"
echo "Apply both : the builders in the cluster are the reference for the next runs."
