META_MONGO_IP : "141.115.103.31"
OPENSTACK_SWIFT_IP : "141.115.103.30"
GOLD_MONGO_IP : "141.115.103.33"
GOLD_NEO4J_IP : "141.115.103.33"
GOLD_INFLUX_IP : "141.115.103.33"
MONGO_PORT : "27017"
SWIFT_REST_API_PORT : "8080"
INFLUXDB_PORT : "8086"
NEO4J_PORT : "7000"
SWIFT_USER : 'test:tester'
SWIFT_KEY : 'testing'
MONGO_META_CONN_ID : "mongo_metadatabase"
MONGO_GOLD_CONN_ID =: "mongo_gold"
