all:
  children:
    metadata_management_zone:
      hosts:
        metadata_management_zone_mongodb:
          ansible_ssh_private_key_file: "{{inventory_dir}}/host_vars/.ssh/test_ansible"
          ansible_host: 127.0.0.1
          # Use if you don't have a sudoers without password
          ansible_sudo_pass:
          ansible_port: 22
        metadata_management_zone_neo4j:
          ansible_ssh_private_key_file: "{{inventory_dir}}/host_vars/.ssh/test_ansible"
          ansible_host: 127.0.0.1
          ansible_port: 22
    raw_data_zone:
      hosts:
        raw_data_zone_openstack_swift:
          ansible_ssh_private_key_file: "{{inventory_dir}}/host_vars/.ssh/test_ansible"
          ansible_host: 127.0.0.1
          ansible_port: 22
    process_zone:
      hosts:
        process_zone_apache_airflow:
          ansible_ssh_private_key_file: "{{inventory_dir}}/host_vars/.ssh/test_ansible"
          ansible_host: 127.0.0.1
          ansible_port: 22
        process_zone_apache_spark:
          ansible_ssh_private_key_file: "{{inventory_dir}}/host_vars/.ssh/test_ansible"
          ansible_host: 127.0.0.1
          ansible_port: 22
    processed_data_zone:
      hosts:
        processed_data_zone_influxdb:
          ansible_ssh_private_key_file: "{{inventory_dir}}/host_vars/.ssh/test_ansible"
          ansible_host: 127.0.0.1
          ansible_port: 22
        processed_data_zone_mongodb:
          ansible_ssh_private_key_file: "{{inventory_dir}}/host_vars/.ssh/test_ansible"
          ansible_host: 127.0.0.1
          ansible_port: 22
    security_authentication_monitoring_zone:
      hosts:
        security_authentication_monitoring_zone_openstack_keystone:
          ansible_ssh_private_key_file: "{{inventory_dir}}/host_vars/.ssh/test_ansible"
          ansible_host: 127.0.0.1
          ansible_port: 22
        security_authentication_monitoring_zone_kerberos:
          ansible_ssh_private_key_file: "{{inventory_dir}}/host_vars/.ssh/test_ansible"
          ansible_host: 127.0.0.1
          ansible_port: 22
    service_zone:
      hosts:
        service_zone_web_gui:
          ansible_ssh_private_key_file: "{{inventory_dir}}/host_vars/.ssh/test_ansible"
          ansible_host: 127.0.0.1
          ansible_port: 22
        service_zone_rest_api:
          ansible_ssh_private_key_file: "{{inventory_dir}}/host_vars/.ssh/test_ansible"
          ansible_host: 127.0.0.1
          ansible_port: 22


